name: Lint
on: [pull_request, push]

jobs:
  build:
    env:
    runs-on: ubuntu-latest
    name: Lint
    strategy:
      matrix:
        ruby:
          - '3.2.2'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Install dependencies
        run: |
          bundle config set without 'production staging test'
          bundle install
          git checkout Gemfile.lock

      - name: Get file changes
        id: get_file_changes
        uses: dorner/file-changes-action@v1.2.0
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          plaintext: true

      - name: Echo file changes
        run: |
          echo Changed files: ${{ steps.get_file_changes.outputs.files }}

      - name: Run RuboCop on changed files
        run: |
          if [ -n "${{ steps.get_file_changes.outputs.files }}" ]; then
            bundle exec rubocop --fail-level C ${{ steps.get_file_changes.outputs.files }}
          else
            echo "No files changed"
          fi
