name: Lint Code With RuboCop

on:
  pull_request:
    paths:
      - '**/*.rb'
  push:
    paths:
      - '**/*.rb'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install dependencies
        run: |
          bundle config set without 'production staging test'
          bundle install

      - name: Get file changes
        id: get_file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          output: ' '

      - name: Filter files based on RuboCop exclusions
        id: filter_files
        run: |
          # Read the excluded paths from the RuboCop configuration
          excluded_paths=$(ruby -r yaml -e 'puts YAML.load_file(".rubocop.yml")["AllCops"]["Exclude"].join(" ")')
          echo "Excluded paths: $excluded_paths"

          # Get list of changed files
          files=$(echo "${{ steps.get_file_changes.outputs.files }}" | tr ' ' '\n')

          # Filter out the excluded paths from the changed files
          filtered_files=""
          for file in $files; do
            exclude=false
            for pattern in $excluded_paths; do
              if [[ "$file" == *"$pattern"* ]]; then
                exclude=true
                break
              fi
            done <<< "$excluded_paths"
            if [ "$exclude" = false ]; then
              filtered_files="$filtered_files $file"
            fi
          done

          echo "Filtered files: $filtered_files"
          echo "filtered_files=$filtered_files" >> $GITHUB_ENV

      - name: Echo filtered files
        run: echo "Filtered files ${{ env.filtered_files }}"

      - name: Run RuboCop on filtered files
        run: |
          files="${{ env.filtered_files }}"
          if [ -n "$files" ]; then
            echo "Running RuboCop on changed Ruby files..."
            bundle exec rubocop $files
          else
            echo "No Ruby files changed"
          fi
