name: RuboCop Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3 --without production

      - name: Get list of modified files
        id: modified_files
        run: |
          echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.rb$' | xargs)"

      - name: Run RuboCop on modified files
        run: |
          if [ -n "${{ steps.modified_files.outputs.files }}" ]; then
            echo "Running RuboCop on the following files:"
            echo "${{ steps.modified_files.outputs.files }}"
            bundle exec rubocop ${{ steps.modified_files.outputs.files }}
          else
            echo "No Ruby files modified."
          fi

