name: Lint Code With RuboCop

on:
  pull_request:
    paths:
      - '**.rb'
  push:
    paths:
      - '**.rb'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install dependencies
        run: |
          bundle config set without 'production staging test'
          bundle install

      - name: Get file changes
        id: get_file_changes
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          git diff --name-only ${{ github.base_ref }} ${{ github.sha }} > changed_files.txt

      - name: Echo file changes
        run: |
          cat changed_files.txt

      - name: Run RuboCop on changed files
        run: |
          if [ -s changed_files.txt ]; then
            files=$(cat changed_files.txt | grep '\.rb$' | tr '\n' ' ')
            if [ -n "$files" ]; then
              bundle exec rubocop $files
            else
              echo "No Ruby files changed"
            fi
          else
            echo "No files changed"
          fi
