name: Lint
on: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby {{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2.2'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Install dependencies
        run: |
          bundle config set without 'production test'
          bundle install --with development

      - name: Run RuboCop
        run: bundle exec rubocop

